### PR TITLE
micro car version of ottoLogger.py -> trying out github. Am I helping?

### PR DESCRIPTION
**Pull request by digsrus**
This is a temporary file just to see if I am in the ballpark for what you are looking for.

### CODE REVIEW

**Comment by digsrus** [comment]
My intention was to implement your ideas for the button/switch/LEDs but didn't want to muck up the main ottoLogger.py program until you looked it over. I figured the otto, ottoMini and ottoMicro cars would have pretty much the same ottoLogger.py program with just different pin assignments.

**Comment by digsrus** [comment]
Error handling added. Big League.

**Comment by ricklon** [comment]
I see this is closed. The changes are really good. I saw new changes yesterday. I haven't added it yet. Did you want to make more changes or do this as a separate pull request?

**Comment by digsrus** [comment]
I just wanted to show what progress I had made. There is quite a bit that has to be completed yet and didn’t mean to close the file. I am still using training wheels with github and your talk tomorrow is just what I need.

**Pull request merged**
